# Generated by Django 6.0.4 on 2026-04-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.studentgroup'),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='courses.studentgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.branch'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to='courses.student'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.student'),
        ),
        migrations.AlterField(
            model_name='subscriptionplansubject',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subjects', to='courses.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lesson')},
        ),
    ]
